name: Konstellation Secrets Scanning

on:
  push:
    tags:
      - '*'
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Secrets scanning
        uses: trufflesecurity/trufflehog@main
        with:
          path: ${{ github.GITHUB_WORKSPACE }}
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
